name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./booking-api/gradlew

      - name: Run tests
        working-directory: ./booking-api
        run: ./gradlew test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: booking-api/build/reports/tests/test
